# -*- coding: utf-8 -*-
"""
Created on Sat Jul 26 16:10:49 2025

@author: Orhan
"""

import pickle
import re
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

# Eğitim verisi
training_data = [
    ("What's the job openings in Beijing?", True),
    ("Dubai currency rate today", True),
    ("What's the exhibitions in Istanbul?", True),
    ("Los Angeles currency rate today", True),
    ("What's the exhibitions in Istanbul?", True),
    ("What's the concerts in Tokyo?", True),
    ("What's the job openings in Cairo?", True),
    ("What's the weather in Berlin?", True),
    ("What's the concerts in Beijing?", True),
    ("What's the exhibitions in Cairo?", True),
    ("What's the job openings in Berlin?", True),
    ("Istanbul currency rate today", True),
    ("What's the weather in Los Angeles?", True),
    ("What's the job openings in Istanbul?", True),
    ("What's the events in Mumbai?", True),
    ("What's the concerts in Tokyo?", True),
    ("What's the news in Beijing?", True),
    ("What's the concerts in Mumbai?", True),
    ("Top rated best hotels in Istanbul?", True),
    ("What's the restaurant in Mumbai?", True),
    ("What's the job openings in Istanbul?", True),
    ("What's the exhibitions in Istanbul?", True),
    ("What's the job openings in Berlin?", True),
    ("What's the restaurant in Cairo?", True),
    ("What's the traffic in Tokyo?", True),
    ("What's the exhibitions in Mumbai?", True),
    ("What's the weather in Istanbul?", True),
    ("What's the exhibitions in Tokyo?", True),
    ("What's the weather in Paris?", True),
    ("Cairo currency rate today", True),
    ("Top rated best hotels in Istanbul?", True),
    ("What's the events in Cairo?", True),
    ("Cairo currency rate today", True),
    ("Top rated best hotels in Paris?", True),
    ("What's the traffic in Beijing?", True),
    ("What's the restaurant in Dubai?", True),
    ("What's the restaurant in Cairo?", True),
    ("What's the traffic in Paris?", True),
    ("What's the traffic in Beijing?", True),
    ("What's the restaurant in Dubai?", True),
    ("What's the weather in Paris?", True),
    ("What's the job openings in New York?", True),
    ("What's the news in New York?", True),
    ("What's the weather in New York?", True),
    ("What's the events in Cairo?", True),
    ("What's the restaurant in Paris?", True),
    ("What's the traffic in Paris?", True),
    ("What's the news in Beijing?", True),
    ("What's the restaurant in New York?", True),
    ("What's the traffic in Istanbul?", True),
    ("What's the restaurant in Paris?", True),
    ("What's the weather in Beijing?", True),
    ("What's the news in Cairo?", True),
    ("What's the news in Dubai?", True),
    ("Top rated best hotels in Berlin?", True),
    ("What's the weather in Cairo?", True),
    ("What's the restaurant in Los Angeles?", True),
    ("What's the exhibitions in Los Angeles?", True),
    ("Top rated best hotels in Paris?", True),
    ("What's the news in Los Angeles?", True),
    ("What's the events in Dubai?", True),
    ("Cairo currency rate today", True),
    ("Beijing currency rate today", True),
    ("What's the exhibitions in Beijing?", True),
    ("What's the weather in Cairo?", True),
    ("What's the traffic in Mumbai?", True),
    ("Top rated best hotels in Mumbai?", True),
    ("Paris currency rate today", True),
    ("What's the concerts in Dubai?", True),
    ("What's the events in Dubai?", True),
    ("What's the weather in Beijing?", True),
    ("What's the concerts in Paris?", True),
    ("What's the restaurant in Dubai?", True),
    ("Top rated best hotels in Los Angeles?", True),
    ("What's the restaurant in Dubai?", True),
    ("What's the traffic in Tokyo?", True),
    ("What's the restaurant in Berlin?", True),
    ("What's the news in New York?", True),
    ("Top rated best hotels in Paris?", True),
    ("What's the restaurant in Los Angeles?", True),
    ("New York currency rate today", True),
    ("What's the news in New York?", True),
    ("What's the weather in Los Angeles?", True),
    ("What's the restaurant in Beijing?", True),
    ("What's the job openings in Los Angeles?", True),
    ("Top rated best hotels in Dubai?", True),
    ("What's the restaurant in Tokyo?", True),
    ("What's the news in Dubai?", True),
    ("What's the events in Mumbai?", True),
    ("What's the job openings in New York?", True),
    ("What's the weather in Mumbai?", True),
    ("Top rated best hotels in Paris?", True),
    ("Top rated best hotels in Tokyo?", True),
    ("What's the exhibitions in Dubai?", True),
    ("What's the job openings in Berlin?", True),
    ("What's the exhibitions in Berlin?", True),
    ("What's the job openings in Paris?", True),
    ("Istanbul currency rate today", True),
    ("What's the events in Dubai?", True),
    ("What's the restaurant in Cairo?", True),
    ("What's the news in Los Angeles?", True),
    ("What's the weather in Los Angeles?", True),
    ("What's the job openings in Istanbul?", True),
    ("What's the job openings in Beijing?", True),
    ("What's the weather in Beijing?", True),
    ("What's the job openings in Cairo?", True),
    ("What's the job openings in Paris?", True),
    ("What's the restaurant in Los Angeles?", True),
    ("Top rated best hotels in Beijing?", True),
    ("What's the concerts in Los Angeles?", True),
    ("Paris currency rate today", True),
    ("What's the concerts in Dubai?", True),
    ("What's the traffic in Tokyo?", True),
    ("What's the news in Tokyo?", True),
    ("Top rated best hotels in Beijing?", True),
    ("What's the restaurant in Berlin?", True),
    ("What's the traffic in Paris?", True),
    ("Top rated best hotels in Dubai?", True),
    ("Top rated best hotels in Istanbul?", True),
    ("What's the exhibitions in Paris?", True),
    ("What's the job openings in Paris?", True),
    ("Istanbul currency rate today", True),
    ("What's the events in Los Angeles?", True),
    ("Top rated best hotels in Cairo?", True),
    ("What's the exhibitions in Beijing?", True),
    ("What's the weather in Cairo?", True),
    ("Top rated best hotels in Mumbai?", True),
    ("What's the exhibitions in Berlin?", True),
    ("What's the weather in Mumbai?", True),
    ("Top rated best hotels in Beijing?", True),
    ("What's the exhibitions in Cairo?", True),
    ("New York currency rate today", True),
    ("What's the events in Paris?", True),
    ("What's the restaurant in Berlin?", True),
    ("What's the concerts in New York?", True),
    ("What's the events in Cairo?", True),
    ("What's the traffic in Tokyo?", True),
    ("What's the weather in Paris?", True),
    ("Istanbul currency rate today", True),
    ("What's the news in Tokyo?", True),
    ("Top rated best hotels in Beijing?", True),
    ("What's the concerts in Beijing?", True),
    ("Top rated best hotels in Tokyo?", True),
    ("What's the weather in Paris?", True),
    ("What's the events in Istanbul?", True),
    ("What's the events in Paris?", True),
    ("What's the exhibitions in Dubai?", True),
    ("What's the job openings in Cairo?", True),
    ("What's the weather in Istanbul?", True),
    ("Tokyo currency rate today", True),
    ("What's the news in Beijing?", True),
    ("What's the exhibitions in Paris?", True),
    ("What's the traffic in Cairo?", True),
    ("What's the restaurant in Istanbul?", True),
    ("What's the news in Dubai?", True),
    ("What's the concerts in Beijing?", True),
    ("What's the exhibitions in Dubai?", True),
    ("What's the weather in Cairo?", True),
    ("What's the weather in Paris?", True),
    ("Tokyo currency rate today", True),
    ("What's the events in Cairo?", True),
    ("What's the news in Dubai?", True),
    ("What's the weather in Dubai?", True),
    ("What's the news in Dubai?", True),
    ("What's the events in Dubai?", True),
    ("Los Angeles currency rate today", True),
    ("Top rated best hotels in Los Angeles?", True),
    ("What's the events in Beijing?", True),
    ("What's the traffic in Los Angeles?", True),
    ("What's the events in Istanbul?", True),
    ("What's the traffic in Los Angeles?", True),
    ("What's the events in Mumbai?", True),
    ("What's the news in Dubai?", True),
    ("What's the job openings in Berlin?", True),
    ("What's the events in Istanbul?", True),
    ("What's the weather in Los Angeles?", True),
    ("Top rated best hotels in Berlin?", True),
    ("What's the concerts in Tokyo?", True),
    ("What's the news in Beijing?", True),
    ("What's the job openings in Istanbul?", True),
    ("What's the traffic in Tokyo?", True),
    ("What's the restaurant in Dubai?", True),
    ("What's the weather in Paris?", True),
    ("What's the events in Berlin?", True),
    ("What's the restaurant in Tokyo?", True),
    ("Top rated best hotels in New York?", True),
    ("What's the traffic in Istanbul?", True),
    ("What's the traffic in Berlin?", True),
    ("What's the exhibitions in Beijing?", True),
    ("Top rated best hotels in Tokyo?", True),
    ("What's the exhibitions in Paris?", True),
    ("What's the events in Beijing?", True),
    ("What's the exhibitions in Dubai?", True),
    ("What's the exhibitions in Beijing?", True),
    ("What's the concerts in Istanbul?", True),
    ("Top rated best hotels in Mumbai?", True),
    ("What's the restaurant in Cairo?", True),
    ("Top rated best hotels in Tokyo?", True),
    ("What's the job openings in Tokyo?", True),
    ("What's the job openings in Berlin?", True),

    ("Principle Of water.", False),
    ("Principle Of French.", False),
    ("What is the capital of French?", False),
    ("Process Of water.", False),
    ("Translate 'friend' to gravity", False),
    ("Translate 'friend' to water", False),
    ("Define photosynthesis.", False),
    ("What is the capital of Einstein?", False),
    ("History Venus.", False),
    ("Steps Of gravity.", False),
    ("Explain World War I.", False),
    ("Principle Of Venus.", False),
    ("Translate 'friend' to Venus", False),
    ("Boiling Point photosynthesis.", False),
    ("Boiling Point Venus.", False),
    ("Boiling Point machine learning.", False),
    ("Explain World War I.", False),
    ("History photosynthesis.", False),
    ("Explain World War I.", False),
    ("Boiling Point gravity.", False),
    ("Laws Of photosynthesis.", False),
    ("Laws Of gravity.", False),
    ("Laws Of machine learning.", False),
    ("Steps Of photosynthesis.", False),
    ("Explain Einstein.", False),
    ("Define Einstein.", False),
    ("What is the capital of Venus?", False),
    ("Define World War I.", False),
    ("Steps Of gravity.", False),
    ("Boiling Point French.", False),
    ("Define Venus.", False),
    ("History Einstein.", False),
    ("Laws Of photosynthesis.", False),
    ("Principle Of World War I.", False),
    ("What is the capital of Einstein?", False),
    ("Explain machine learning.", False),
    ("Steps Of gravity.", False),
    ("History Einstein.", False),
    ("Boiling Point photosynthesis.", False),
    ("What is the capital of World War I?", False),
    ("Process Of World War I.", False),
    ("Explain French.", False),
    ("Translate 'friend' to Einstein", False),
    ("What is the capital of gravity?", False),
    ("What is the capital of Einstein?", False),
    ("Define Einstein.", False),
    ("History World War I.", False),
    ("What is the capital of gravity?", False),
    ("Boiling Point World War I.", False),
    ("Translate 'friend' to Einstein", False),
    ("Laws Of World War I.", False),
    ("Explain Venus.", False),
    ("Principle Of water.", False),
    ("History water.", False),
    ("History machine learning.", False),
    ("History Einstein.", False),
    ("Explain Einstein.", False),
    ("What is the capital of Venus?", False),
    ("Translate 'friend' to gravity", False),
    ("What is the capital of French?", False),
    ("Laws Of French.", False),
    ("Principle Of gravity.", False),
    ("History French.", False),
    ("Boiling Point machine learning.", False),
    ("Boiling Point water.", False),
    ("Laws Of World War I.", False),
    ("What is the capital of World War I?", False),
    ("What is the capital of water?", False),
    ("Define machine learning.", False),
    ("History French.", False),
    ("History gravity.", False),
    ("Translate 'friend' to photosynthesis", False),
    ("Boiling Point machine learning.", False),
    ("Translate 'friend' to water", False),
    ("Define Venus.", False),
    ("Explain gravity.", False),
    ("Boiling Point machine learning.", False),
    ("Define water.", False),
    ("Translate 'friend' to French", False),
    ("Explain photosynthesis.", False),
    ("Process Of Venus.", False),
    ("Principle Of World War I.", False),
    ("Explain gravity.", False),
    ("History gravity.", False),
    ("What is the capital of gravity?", False),
    ("Process Of photosynthesis.", False),
    ("Boiling Point photosynthesis.", False),
    ("Process Of water.", False),
    ("Laws Of gravity.", False),
    ("Principle Of machine learning.", False),
    ("History gravity.", False),
    ("History French.", False),
    ("Laws Of World War I.", False),
    ("Process Of water.", False),
    ("Process Of French.", False),
    ("What is the capital of water?", False),
    ("Laws Of French.", False),
    ("Process Of Venus.", False),
    ("Principle Of gravity.", False),
    ("Define machine learning.", False),
    ("Define Einstein.", False),
    ("What is the capital of French?", False),
    ("Boiling Point machine learning.", False),
    ("Laws Of World War I.", False),
    ("What is the capital of machine learning?", False),
    ("Process Of Einstein.", False),
    ("Process Of World War I.", False),
    ("Explain Venus.", False),
    ("Translate 'friend' to water", False),
    ("Principle Of Einstein.", False),
    ("History World War I.", False),
    ("Boiling Point World War I.", False),
    ("Process Of machine learning.", False),
    ("Boiling Point Venus.", False),
    ("Explain machine learning.", False),
    ("Laws Of machine learning.", False),
    ("History water.", False),
    ("Explain gravity.", False),
    ("Boiling Point gravity.", False),
    ("Boiling Point World War I.", False),
    ("History Venus.", False),
    ("Define World War I.", False),
    ("Define Einstein.", False),
    ("Process Of Venus.", False),
    ("Boiling Point World War I.", False),
    ("Steps Of gravity.", False),
    ("Define Einstein.", False),
    ("Explain World War I.", False),
    ("Laws Of water.", False),
    ("What is the capital of gravity?", False),
    ("Laws Of World War I.", False),
    ("Define gravity.", False),
    ("What is the capital of water?", False),
    ("Translate 'friend' to water", False),
    ("Principle Of Venus.", False),
    ("History Venus.", False),
    ("Translate 'friend' to Venus", False),
    ("Explain World War I.", False),
    ("Laws Of machine learning.", False),
    ("Process Of water.", False),
    ("History Venus.", False),
    ("What is the capital of gravity?", False),
    ("Steps Of photosynthesis.", False),
    ("Define photosynthesis.", False),
    ("What is the capital of World War I?", False),
    ("Process Of French.", False),
    ("Translate 'friend' to World War I", False),
    ("Laws Of Venus.", False),
    ("Laws Of water.", False),
    ("History photosynthesis.", False),
    ("Explain photosynthesis.", False),
    ("What is the capital of World War I?", False),
    ("What is the capital of gravity?", False),
    ("Define World War I.", False),
    ("History Venus.", False),
    ("Process Of Einstein.", False),
    ("Explain French.", False),
    ("History World War I.", False),
    ("Laws Of Einstein.", False),
    ("Boiling Point World War I.", False),
    ("Process Of Venus.", False),
    ("Boiling Point gravity.", False),
    ("History World War I.", False),
    ("Translate 'friend' to water", False),
    ("Principle Of Einstein.", False),
    ("Define photosynthesis.", False),
    ("Translate 'friend' to photosynthesis", False),
    ("Process Of water.", False),
    ("What is the capital of gravity?", False),
    ("Boiling Point Einstein.", False),
    ("Process Of water.", False),
    ("Steps Of machine learning.", False),
    ("History French.", False),
    ("Translate 'friend' to water", False),
    ("Boiling Point machine learning.", False),
    ("What is the capital of French?", False),
    ("Steps Of World War I.", False),
    ("Steps Of Einstein.", False),
    ("Steps Of Venus.", False),
    ("Translate 'friend' to machine learning", False),
    ("History water.", False),
    ("History World War I.", False),
    ("Steps Of World War I.", False),
    ("Translate 'friend' to water", False),
    ("Principle Of photosynthesis.", False),
    ("History Venus.", False),
    ("Laws Of Venus.", False),
    ("History water.", False),
    ("Laws Of machine learning.", False),
    ("Explain gravity.", False),
    ("Steps Of World War I.", False),
    ("Process Of French.", False),
    ("Laws Of Einstein.", False),
    ("Define gravity.", False),
    ("Laws Of Venus.", False),
    ("Process Of photosynthesis.", False),
    ("History World War I.", False),
    ("Principle Of French.", False),
    ("Steps Of photosynthesis.", False),
    ("Steps Of water.", False),
]


# Ön işleme fonksiyonu
def preprocess_text(text):
    contractions = {
        "what's": "what is",
        "who's": "who is",
        "i'm": "i am",
        "it's": "it is",
        "don't": "do not",
        "can't": "cannot",
        "doesn't": "does not",
        "isn't": "is not",
        "aren't": "are not",
        "won't": "will not",
        "didn't": "did not",
        "hasn't": "has not",
    }
    text = text.lower()
    for k, v in contractions.items():
        text = re.sub(rf"\b{k}\b", v, text)
    return text

# Embedder ve model pipeline
questions, labels = zip(*training_data)
embedder = SentenceTransformer("all-MiniLM-L6-v2")
X = embedder.encode([preprocess_text(q) for q in questions])
clf_pipeline = make_pipeline(StandardScaler(), LogisticRegression())
clf_pipeline.fit(X, labels)

# Ana fonksiyon: Dışa açılacak
def web_required_classifier(question):
    preprocessed = preprocess_text(question)
    vec = embedder.encode([preprocessed])
    return clf_pipeline.predict(vec)[0]
